### PR TITLE
Add upgrading doc

### PR DESCRIPTION
**Pull request by pgunn**
How does this look?

### CODE REVIEW

**Comment by epnev** [comment]
Can you enrich it explaining also what happens if somebody installed using the "-e" option?

**Comment by pgunn** [comment]
I initially had done that, but the steps are the same.

**Comment by epnev** [comment]
In my case a simple git pull appears to be working all the time. 
We should also link to this info in the readme and potentially putting it on the wiki. We're accumulating too many .md files in the main folder. I'm pretty sure very few people click on them.

**Comment by pgunn** [comment]
A simple pull won't rebuild the c++ code, and won't refresh the conda environment; if neither changes that is fine.

**Comment by epnev** [comment]
Closing, added to [wiki](https://github.com/flatironinstitute/CaImAn/wiki/Updating-CaImAn).

**Pull request closed without merging**
