### PR TITLE
check if ipyparallel cluster is running, avoid waiting blindly

### PR DESCRIPTION
**Pull request by histed**
Waits for all workers to execute a placeholder bit of code.

Signed-off-by: Mark Histed <mhisted@gmail.com>

### CODE REVIEW

**Comment by agiovann** [comment]
dear @histed thank you so much for the feedback and contribution. Have you tried it on multiple platforms? In the past I was having problems under linux or mac (cannot remember...).

**Comment by pgunn** [comment]
@histed When you get the time, I've made a revised version of this against current sources here:
https://pastebin.com/VT4vbGuB

If you can review that for intent that'd be great. If you want to update your diff with it, that's also great.

**Comment by agiovann** [comment]
@pgunn why are there conflicts here? Is this supposed to be merged?

**Comment by pgunn** [comment]
He did the diff some time back and the file has since changed. I did a rewrite and put it in the pastebin above; I'd like him to review it for intent and either update his diff or close it and I can do a new PR. Waiting to hear back from him.

**Comment by histed** [comment]
Hi, sorry for delay.

I looked at the pastebin snippet code, only reviewing the ipyparallel (not slurm) case.
This looks correct.  My intent was to use dview().execute(block=True), which runs code on all workers and returns only when each ran successfully, to confirm the ipyparallel cluster was fully started.  That seems intact.

@pgunn it looks like you've retained client.close().  I haven't tested, but I think

**Comment by pgunn** [comment]
That seems sensible; would you mind reworking this PR against the current version of dev with whatever revisions to the pastebin code you'd like? Alternatively we could close this PR and I could make a new one.

**Comment by pgunn** [comment]
Hey - I'd love if you can get back to me on the last question above, but if not I'll close this early next week and commit the version in pastebin, likely incorporating your suggestion, after some testing.

**Comment by pgunn** [comment]
Closing this ; PR #281 is the successor.

**Pull request closed without merging**
