### PR TITLE
Switch mac environment to conda-forge and python3

### PR DESCRIPTION
**Pull request by pgunn**
This passes nosetests; we should test it throughly before landing

### CODE REVIEW

**Comment by dylex** [comment]
Does this let us get rid of the hacky for loop around nosetests on osx too?

**Comment by pgunn** [comment]
I can try removing it; I'm not sure what that loop was for.

**Comment by dylex** [comment]
nosetests on osx (at least that version) used some hacky way to load modules when you passed it (implicit) python files rather than module names, which broke stuff.

**Comment by pgunn** [comment]
Ah, interesting. If that's still an issue, we can have conda install a specific version of nose with the features we need.

**Comment by j-friedrich** [comment]
is there a reason to still use pip for tifffile and peakutils? The conda-forge versions worked fine on my Mac and it seems easier to not mix conda and pip if you don't have to.

**Comment by dylex** [comment]
You should probably merge dev into your branch -- it might fix these random build failures.

**Pull request merged**
