### PR TITLE
Fix incompatibilities in test_sbx for python <3.11

### PR DESCRIPTION
**Pull request by ethanbb**
# Description

Fixes build error in #1311 

# Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Has your PR been tested?

```caimanmanager test``` passes on 3.11 - if any invalid syntax for <3.11 remains, should be caught in CI

### CODE REVIEW

**Comment by ethanbb** [comment]
Well looks like the nice type annotation syntax doesn't work on 3.9... updating now

**Comment by pgunn** [comment]
Looks like the type annotation syntax is also not compatible with 3.9:
```
  File "/home/runner/work/CaImAn/CaImAn/caiman/utils/sbx_utils.py", line 14, in <module>
    DimSubindices = Iterable[int] | slice
TypeError: unsupported operand type(s) for |: '_GenericAlias' and 'type'
```

We're looking forward to pushing our python dependency to 3.10-3.12 for a lot of reasons, but we're not quite ready to do so yet.

**Comment by pgunn** [comment]
At least stuff like this reminds us that python is getting better! I think there were just some upstream packaging issues that currently block us from switching over (tensorflow and one other thing, I think); when we do I'm looking forward to going through the codebase and modernising the syntax (my favourite kind of diff to work on)

**Comment by pgunn** [comment]
Thanks! I'll be cutting a new release shortly (today or tomorrow); mostly a bugfix for the thing you found earlier that I thought was already out, but your sbx fix here will also be part of it; you won't need to use a compiled build for very long (unless you want to).

**Comment by ethanbb** [comment]
Great, thank you for being so responsive and helping me get this out!

**Comment by kushalkolar** [comment]
I'm think this is py3.10+ https://peps.python.org/pep-0604/ 

according to [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html) python3.9 support stops in numpy on April 5 so it's not too far out, but tensorflow usually lags behind quite a bit.

**Pull request merged**
