### PR TITLE
Issue880

### PR DESCRIPTION
**Pull request by j-friedrich**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (880)

# Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

# Branching

- Pull requests with non breaking bug fixes should be made against the **master** branch.
- All other PRs should be made against the **dev** branch.

# Has your PR been tested?

Yes

### CODE REVIEW

**Comment by pgunn** [comment]
Looks good; merge whenever it goes green or you otherwise like.

**Comment by pgunn** [comment]
@j-friedrich  Oh, hang on, do you mind merging this to dev instead? I'm trying to have all diffs go to dev, never to master. If you need it released, poke me and I'll merge to master and cut a release to get it into a conda package.

**Comment by j-friedrich** [comment]
Ok, will merge to dev instead. That has been my usual procedure, but the PR
template says to merge with master if it doesn't break things.

**Comment by pgunn** [comment]
I'll go looking for the template to adjust that guidance. Thanks.

**Pull request merged**
