### PR TITLE
Volpy notebook

### PR DESCRIPTION
**Pull request by caichangjia**
# Description
Add ipython notebook for VolPy.

### CODE REVIEW

**Comment by pgunn** [comment]
It might be tidier to "Restart and clear output" on the notebook first

**Comment by EricThomson** [comment]
A few minor comments on things probably not needed outside of colab context:

    if __IPYTHON__:
        # this is used for debugging purposes only. allows to reload classes
        # when changed

    
    save the movie in the mp4 format

Note for me it breaks at the `utils.mrcnn_inference` step (it finds no ROIs). I can't see why: at the colab nb it works fine, I seem to have everything installed in my environment. Not sure how much I want to make of this in a PR my guess is if it is an issue people will report it, or I will  once I've had time to properly investigate. That step works fine in colab. I'll have time to look at this more closely next week.

**Comment by EricThomson** [comment]
> if __IPYTHON__:
>     # this is used for debugging purposes only. allows to reload classes
>     # when changed

Oops Nevermind this part is fine. the snippet about saving as mp4 is the only vestigial colab bit I found.

**Comment by pgunn** [comment]
Small nitpick: Does SEGMENTATION need to be in all-caps? (sorry to pester)

**Comment by caichangjia** [comment]
Eric, the VolPy mrcnn inference problem you mentioned is #1013 which should be solved already. I tested on newly downloaded master branch and it worked.

**Comment by pgunn** [comment]
I'm happy to merge; is it ready?

**Comment by EricThomson** [comment]
I think it is ready, this mask-rcnn bugfix was one release ahead of my version of caiman in my env, oops! Sorry @caichangjia thanks for the addition!

**Pull request merged**
